# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O678tfpCZGgdmRChKTaixFxU5IgEYnqw
"""

import os
import asyncio
import logging
from aiogram import Bot, Dispatcher, types
from aiogram.filters import CommandStart
from ultralytics import YOLO
import cv2
import numpy as np
import io
from dotenv import load_dotenv

load_dotenv()
TOKEN = os.getenv("BOT_TOKEN")

bot = Bot(token=TOKEN)
dp = Dispatcher()

# تحميل نموذج واحد أولاً (غير لاحقًا لكل النماذج)
model = YOLO("yolov8n.pt")  # غير هذا لمسار نموذجك الحقيقي بعد التحميل

@dp.message(CommandStart())
async def start(message: types.Message):
    await message.answer("مرحبا! أرسل صورة السيارة وسأقوم بتحليل الأضرار")

@dp.message(types.ContentType.PHOTO)
async def analyze_photo(message: types.Message):
    try:
        await message.answer("جاري التحليل... انتظر شوية (قد يستغرق 5-20 ثانية)")

        # تحميل الصورة
        photo = await message.photo[-1].download(destination=io.BytesIO())
        img_bytes = photo.getvalue()

        nparr = np.frombuffer(img_bytes, np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

        # تشغيل النموذج
        results = model(img, conf=0.3)

        # عدد الاكتشافات
        damage_count = len(results[0].boxes)
        result_text = f"تم اكتشاف {damage_count} منطقة ضرر محتملة\n\nنتيجة أولية (جاري تطوير النسخة الكاملة)"

        # إنشاء صورة مع التعليقات
        annotated = results[0].plot()
        _, buffer = cv2.imencode(".jpg", annotated)
        annotated_bytes = buffer.tobytes()

        await message.answer_photo(
            photo=types.BufferedInputFile(annotated_bytes, filename="analysis.jpg"),
            caption=result_text
        )

    except Exception as e:
        await message.answer(f"حدث خطأ: {str(e)}")

async def main():
    logging.basicConfig(level=logging.INFO)
    await dp.start_polling(bot)

if __name__ == "__main__":
    asyncio.run(main())